### ISSUE TITLE
program crashes very often

### ISSUE THREAD

**Issue by Cryogenus** [coderslagoon/BadPeggy#3]
Good morning.

Please tell me what can be done so that Bud Peggy does not crash about checking images. Or at least how to find a list of files that the program has already managed to find. I would also like to find the file on which the program crashed.

I had some images and, apparently, remained when the program immediately crashes when checking. Only the hs_err_pid file appears (example hs_err_pid21348.log) and that's it.

[hs_err_pid25012.log](https://github.com/coderslagoon/BadPeggy/files/8448787/hs_err_pid25012.log)

I found several such files and fixed some of them, and deleted some of them. There are still some broken files left and I would like to find them too, but it does not work. There are a lot of files (about 250 thousand).

**Comment by coderslagoon** [comment]
Crash happens deep in the _JPEGImageReader_, something about an exception coming from native imaging code and not being able to get caught(?) correctly. Perhaps similar to https://bugs.openjdk.java.net/browse/JDK-8180347

I'm going to update to the latest Java 17 JRE soon, maybe they have fixed this issue then. Alternative would be to replace the Java 1.8 JRE shipped with the latest version available and try again.

BP doesn't write a log file at this moment (it has emission built in, but a writer was never added). Going to add this too regarding this bug, so in the future the problematic image file might be located.

**Comment by coderslagoon** [comment]
Hope that with the upcoming version 2.4.0 and the bump to Java 17 things get more stable.
Added a logging feature (c6a1360), so the last file(s) before the crash should be reported.
